Reaction tangent controller
termi-official/Thunderbolt.jl pull request #138
Opened 2024-08-14 19:44 UTC by AbdAlazezAhmed

2024-08-14 20:21 UTC, termi-official requested changes
Thanks, this already looks great! I found some things which we should address before merge.

2024-08-14 20:21 UTC, termi-official commented on src/solver/adaptivity.jl
> +    integrator._dt = get_next_dt(controller)
TODO for later PR: Need to check if `_dt` is redundant and if we can confirm, simplify the logic.

2024-08-14 20:21 UTC, termi-official commented on src/solver/adaptivity.jl
> +        subintegrator.f isa PointwiseODEFunction || continue
Docs for the posterity pls.

2024-08-14 20:21 UTC, termi-official commented on src/solver/adaptivity.jl
> +        return maximum(@view subintegrator.cache.dumat[:, φₘidx])
Does this allocate?

2024-08-14 20:21 UTC, termi-official commented on src/solver/adaptivity.jl
> +@inline function OS.update_controller!(integrator::OS.OperatorSplittingIntegrator{<:Any, <:AdaptiveOperatorSplittingAlgorithm{<:OS.LieTrotterGodunov, <:ReactionTangentController}})
Can you control the dispatch via unpacking instead of via the type parameter?

2024-08-14 20:21 UTC, termi-official commented on src/solver/operator_splitting/solver.jl
> +
We should dispatch on https://github.com/SciML/SciMLBase.jl/blob/eb3758cc879093d389b5a8e22753b6ae01e078be/src/alg_traits.jl#L57 for forward compat reasons

2024-08-14 20:21 UTC, termi-official commented on examples/conduction-velocity-benchmark.jl
> +timestepper = Thunderbolt.AdaptiveOperatorSplittingAlgorithm(_timestepper, controller)
The style of the tutorials condenses these with indentations, i.e.
```suggestion
timestepper = Thunderbolt.AdaptiveOperatorSplittingAlgorithm(
    OS.LieTrotterGodunov(
        ...
     ),
     ReactionTangentController(
         ...
     )
```

2024-08-14 20:21 UTC, termi-official commented on src/solver/operator_splitting/integrator.jl
> +@inline update_dt!(::OperatorSplittingIntegrator) = nothing
Not sure if we should do this. I would assume this will hit users who implement custom algorithms later.

2024-08-14 20:21 UTC, termi-official commented on src/solver/operator_splitting/integrator.jl
Any chance we can make the design closer to https://github.com/SciML/OrdinaryDiffEq.jl/blob/master/lib/OrdinaryDiffEqCore/src/integrators/controllers.jl ? These are P, PI and PID controllers which keep the error estimate at certain levels.

2024-08-14 20:21 UTC, termi-official commented on test/test_integrators.jl
> +@testset "OperatorSplitting" begin
Can you add tests for dt's which do not align with the end time, so we can catch regressions here later?

Also, can we add some fake model which NaNs one of the subproblems and check if failure is correctly detected?

2024-08-14 20:21 UTC, termi-official commented on test/test_integrators.jl
> +                DiffEqBase.reinit!(integrator, u0; tspan)
Maybe we should check if the retcode is not Success before solving, i.e.
```suggestion
                DiffEqBase.reinit!(integrator, u0; tspan)
                @test integrator.sol.retcode == DiffEqBase.ReturnCode.Default
```

2024-08-16 21:57 UTC, termi-official requested changes
Thanks! Almost there I think.

2024-08-16 21:57 UTC, termi-official commented on docs/src/assets/references.bib
> +year = {2023}
Format

2024-08-16 21:57 UTC, termi-official commented on docs/src/api-reference/solver.md
> +Thunderbolt.get_reaction_tangent
This is internal API right?

2024-08-16 21:57 UTC, termi-official commented on docs/src/api-reference/solver.md
> +Thunderbolt.AdaptiveOperatorSplittingAlgorithm
This is really not a good algorithm, as in SciML notation this should be an abstract type. Maybe the reaction tangent controller should simply accept the inner solver (LTG and SM)?

2024-08-16 21:57 UTC, termi-official commented on src/solver/adaptivity.jl
> +end
Can we follow the paradigm that we separate out mutable stuff from immutable stuff by caches? (see above to convert this to a solver)

2024-08-16 21:57 UTC, termi-official commented on src/solver/operator_splitting/integrator.jl
> +    synchronize_subintegrators!(integrator)
Do you have a better name for `synchronize_subintegrators!`? Maybe `prepare_step!`?

2024-08-16 21:57 UTC, termi-official commented on test/test_integrators.jl
> +                    # @test integrator_NaN.sol.retcode == DiffEqBase.ReturnCode.Failure
Are these broken?

2024-08-16 21:57 UTC, termi-official commented on test/test_integrators.jl
> +            # @test  isapprox(integrator_adaptive.u, integrator.u, atol=1e-5)
Broken?

2024-08-16 21:57 UTC, termi-official commented on test/test_integrators.jl
> +                # The remaining code works as usual.
Can you add some comments, so we do not forget what we do and simplify away some useful features here? :)

2024-08-16 21:57 UTC, termi-official commented on test/integration/test_electrophysiology.jl
> +    function solve_waveprop(mesh, coeff, subdomains, isadaptive = false)
Maybe this should just accept the solver here?

2024-08-19 13:39 UTC, AbdAlazezAhmed commented on src/solver/operator_splitting/integrator.jl
> +    synchronize_subintegrators!(integrator)
I think `synchronize_subintegrators!` is more descriptive of what the function does. `prepare_step!` sounds a bit ambiguous

2024-08-19 13:40 UTC, AbdAlazezAhmed commented on test/test_integrators.jl
> +                    # @test integrator_NaN.sol.retcode == DiffEqBase.ReturnCode.Failure
The dummy integrator does not return error when the states are NaNed

2024-08-19 13:41 UTC, AbdAlazezAhmed commented on test/test_integrators.jl
> +            # @test  isapprox(integrator_adaptive.u, integrator.u, atol=1e-5)
The adaptive part works only with LTG which is not the function in the test, so it's broken :D yet the adaptive part should be covered in EP tests

2024-08-19 14:47 UTC, termi-official commented on test/test_integrators.jl
> +                    # @test integrator_NaN.sol.retcode == DiffEqBase.ReturnCode.Failure
Should we add another dummy integrator then to test?

2024-08-21 13:57 UTC, termi-official requested changes

2024-08-21 14:04 UTC, AbdAlazezAhmed commented on src/solver/operator_splitting/solver.jl
> +
They exist but not directly here
[https://github.com/termi-official/Thunderbolt.jl/blob/c685bf36968091b854df68a9c8801647f89ce0db/src/solver/adaptivity.jl#L24-L28](https://github.com/termi-official/Thunderbolt.jl/blob/c685bf36968091b854df68a9c8801647f89ce0db/src/solver/adaptivity.jl#L24-L28)

2024-08-28 11:22 UTC, termi-official approved these changes

2024-08-28 11:40 UTC, termi-official requested changes
Okay found a few more things to address when taking another look. Almost there tho.

2024-08-28 11:40 UTC, termi-official commented on src/Thunderbolt.jl
> +import Unrolled: @unroll, unrolled_filter
```suggestion
import Unrolled: @unroll
```

2024-08-28 11:40 UTC, termi-official commented on src/solver/adaptivity.jl
Can we rename this file to `src/solver/time/rtc.jl`?

2024-08-28 11:40 UTC, termi-official commented on src/solver/adaptivity.jl
> +abstract type AbstractTimeAdaptionAlgorithm end
```suggestion
```

2024-08-28 11:40 UTC, termi-official commented on src/solver/adaptivity.jl
> +        throw(ErrorException("Δt is undefined for R = σ_c where σ_s = ∞"))
In the limit $\sigma_s -> \infty$ the sigmoidal function becomes a step function, i.e.
```suggestion
        integrator._dt = R > σ_c ? Δt_bounds[1] : Δt_bounds[2]
```

The analogue for IMEX methods would be the method found in

Whiteley JP. Physiology driven adaptivity for the numerical solution of the bidomain equations. Ann Biomed Eng. 2007; 35(9): 1510-1520. doi:[10.1007/s10439-007-9337-3](https://doi.org/10.1007/s10439-007-9337-3)

2024-08-28 11:40 UTC, termi-official commented on src/solver/adaptivity.jl
> +    const ltg_cache::LTGCache #It has Arrays so it can be const?
```suggestion
    const ltg_cache::LTGCache
```

Yes

2024-08-28 11:40 UTC, termi-official commented on src/solver/adaptivity.jl
> +function OS.init_cache(prob::OS.OperatorSplittingProblem, alg::ReactionTangentController; dt, kwargs...) # TODO
What todo?

2024-08-28 11:40 UTC, termi-official commented on src/solver/adaptivity.jl
> +    Rₙ::T
Why do we need two values? We could do this if we want to restart the time step if Rₙ₊₁ > Rₙ, but usually this should be handled propery by inserting the correct tstops.

2024-08-30 16:08 UTC, merged